// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/prompt/prompt.go

// Package mock_promptutils is a generated GoMock package.
package mock_sso

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPrompter is a mock of Prompter interface.
type MockPrompter struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterMockRecorder
}

// MockPrompterMockRecorder is the mock recorder for MockPrompter.
type MockPrompterMockRecorder struct {
	mock *MockPrompter
}

// NewMockPrompter creates a new mock instance.
func NewMockPrompter(ctrl *gomock.Controller) *MockPrompter {
	mock := &MockPrompter{ctrl: ctrl}
	mock.recorder = &MockPrompterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompter) EXPECT() *MockPrompterMockRecorder {
	return m.recorder
}

// PromptForAccount mocks base method.
func (m *MockPrompter) PromptForAccount() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForAccount")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForAccount indicates an expected call of PromptForAccount.
func (mr *MockPrompterMockRecorder) PromptForAccount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForAccount", reflect.TypeOf((*MockPrompter)(nil).PromptForAccount))
}

// PromptForConfirmation mocks base method.
func (m *MockPrompter) PromptForConfirmation(prompt string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForConfirmation", prompt)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PromptForConfirmation indicates an expected call of PromptForConfirmation.
func (mr *MockPrompterMockRecorder) PromptForConfirmation(prompt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForConfirmation", reflect.TypeOf((*MockPrompter)(nil).PromptForConfirmation), prompt)
}

// PromptForProfile mocks base method.
func (m *MockPrompter) PromptForProfile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForProfile")
	ret0, _ := ret[0].(string)
	return ret0
}

// PromptForProfile indicates an expected call of PromptForProfile.
func (mr *MockPrompterMockRecorder) PromptForProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForProfile", reflect.TypeOf((*MockPrompter)(nil).PromptForProfile))
}

// PromptForRegion mocks base method.
func (m *MockPrompter) PromptForRegion() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForRegion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForRegion indicates an expected call of PromptForRegion.
func (mr *MockPrompterMockRecorder) PromptForRegion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForRegion", reflect.TypeOf((*MockPrompter)(nil).PromptForRegion))
}

// PromptForRole mocks base method.
func (m *MockPrompter) PromptForRole() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForRole")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForRole indicates an expected call of PromptForRole.
func (mr *MockPrompterMockRecorder) PromptForRole() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForRole", reflect.TypeOf((*MockPrompter)(nil).PromptForRole))
}

// PromptForSelection mocks base method.
func (m *MockPrompter) PromptForSelection(label string, items []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForSelection", label, items)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForSelection indicates an expected call of PromptForSelection.
func (mr *MockPrompterMockRecorder) PromptForSelection(label, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForSelection", reflect.TypeOf((*MockPrompter)(nil).PromptForSelection), label, items)
}

// PromptSSOConfiguration mocks base method.
func (m *MockPrompter) PromptSSOConfiguration() (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptSSOConfiguration")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// PromptSSOConfiguration indicates an expected call of PromptSSOConfiguration.
func (mr *MockPrompterMockRecorder) PromptSSOConfiguration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptSSOConfiguration", reflect.TypeOf((*MockPrompter)(nil).PromptSSOConfiguration))
}
