version: 2
project_name: awsctl

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    binary: awsctl
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} # compatibility for the awsctl --version

archives:
  - formats: ["binary"]
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  github:
    owner: berrybytes
    name: awsctl
  release_notes_file: RELEASE_NOTES.md
  extra_files:
    - glob: ./LICENSE
    - glob: ./README.md
    - glob: ./CHANGELOG.md
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
