name: CI Lint And Test with Pre-commit

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Cache pre-commit
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        
    - name: Install Go dependencies
      run: go mod download
      
    - name: Install pre-commit
      run: pip install pre-commit
      
    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure
      
    - name: Run Go tests
      run: go test ./... -v -coverprofile=coverage.txt -covermode=atomic -race
